# Generated by Django 2.2.20 on 2022-01-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='fav_brands',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
