# Generated by Django 2.2.20 on 2023-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Picture'),
        ),
    ]
